### ISSUE TITLE
不能登录账户

### ISSUE THREAD

**Issue by hrdxwandg** [free-vpn/chrome#1]
感谢，希望能坚持，别又挂了。

另外，有个问题，怎么不能登录账号呢？书签没法同步过来

**Comment by 7pitter** [comment]
浏览器很好用，就是不能登录账户，是外国人开发的？

**Comment by 7pitter** [comment]
@free-vpn 那能不能把启动浏览器强制打开你们的主页，这个关掉？浏览器自己的设置里更改不管用，谢谢回复

**Comment by free-vpn** [comment]
@7pitter 就靠启动页面两个广告付服务器账单

**Comment by free-vpn** [comment]
[chrome](https://free-vpn.github.io/chrome/)

**Comment by hrdxwandg** [comment]
@free-vpn 要是能保证服务，另外不仅网页能翻墙，比如git clone操作这种非网页的也能快点就好了。适当收费也能接收呀

**Comment by free-vpn** [comment]
[chrome](https://free-vpn.github.io/chrome/)

**Comment by free-vpn** [comment]
[chrome](https://free-vpn.github.io/chrome/)

**Comment by free-vpn** [comment]
@hrdxwandg 我们vpn也是免费的 mac/ios需要美国ID从store搜索"vpn plus" android直接从网站拿apk windows暂时有问题待修复

**Comment by 7pitter** [comment]
@free-vpn 了解，那就支持你们咯

**Comment by hrdxwandg** [comment]
@free-vpn 能提供非app store下载么，注册了us app id需要visa这些信用卡绑定才能下载。

**Comment by StellaMeow** [comment]
请问windows版本的问题修复了吗？

**Comment by zhangzhe0309** [comment]
感谢分享使用，我这边时断时续的，不知道你们那有没有这个问题

**Comment by hrdxwandg** [comment]
时断时续，我也有这个问题

**Comment by MakeForce** [comment]
@7pitter @hrdxwandg @free-vpn 给大家讲个故事.........故事结论:

> 没有人欠你什么，不要把别人对你的好变成一种习惯，若有一天，你失去了，你就会生不如死

**Comment by 7pitter** [comment]
@free-vpn 就现在，8月8日下午5点，打不开了，启动页也没法打开了，浏览器失效

**Comment by dj9399** [comment]
原来是这个原因不能登录啊。
@free-vpn 非常感谢了，已经加星和推荐给朋友啦

**Comment by daviddongliu** [comment]
希望能在软件里说明不能登录等等问题, 免得大家还得来这里吐槽, 谢谢.感谢努力.

**Comment by itnewgay** [comment]
很好的软件。感谢。

**Comment by WasimZHENG** [comment]
Google網頁上的能登入，為什麼瀏覽器內置G不能登入，無法同步數據啊。總不能裝一臺機器設置一次吧。那麼多插件裝屎人了。

**Comment by free-vpn** [comment]
71配了google api key，可以试试
https://github.com/free-vpn/chrome/releases

如果api调用成本太高，可能不通知诸位直接停用api key，请见谅。

**Comment by wuyow** [comment]
是啊，这个版登陆不了谷歌账号。。。
