### ISSUE TITLE
什么时候能恢复呢？

### ISSUE THREAD

**Issue by naruto1990** [free-vpn/chrome#10]
没有的用好不方便啊

**Comment by KevinWorkSpace** [comment]
windows: by next Tuesday (US Pacific Time, Beijing time - 16 hours)
太平洋时间是周二, 估计咱们得到明天才行, 要今天能出也是晚上了

**Comment by xushanning** [comment]
那只能再等等了

**Comment by KevinWorkSpace** [comment]
新版出来了, 这回没问题了

**Comment by free-vpn** [comment]
已经发布：https://free-vpn.github.io/chrome/

谢谢各位关心

**Comment by xushanning** [comment]
谢谢，可以了~

**Comment by naruto1990** [comment]
赞
