### ISSUE TITLE
Chromium-Windows-69.0.3493.5 加载后闪退

### ISSUE THREAD

**Issue by sysadminadmin** [free-vpn/chrome#11]
您好！开发者
  下载新版本使用时，加载后闪退。查看debug文档，错误内容如下：
ERROR:registration_protocol_win.cc(84)] TransactNamedPipe: 管道已结束。 (0x6D)
ERROR:registration_protocol_win.cc(56)] CreateFile: 系统找不到指定的文件。 (0x2)
请问问题出在哪里，如何解决？

**Comment by wejust1027** [comment]
昨天刚下载使用时出现过闪退情况，但今天一切正常了。

**Comment by sysadminadmin** [comment]
@free-vpn
是全部解压缩出来后运行的。旧版本及旧配置完全删除，新版本解压缩后运行的。

**Comment by Tiandians** [comment]
我这边也经常有闪退的情况。
@free-vpn 请问chromium的正确更新方法是覆盖文件还是完全使用新包？

**Comment by free-vpn** [comment]
@sysadminadmin @Tiandians 完全使用新包，可以把旧版删除，也可以解压到不同目录分开运行。如果频繁闪退，看看是不是开了毒霸，管家这种在后台监控？实在不行我们做个68稳定版chrome。

**Comment by sysadminadmin** [comment]
@free-vpn
完全使用新包，旧版本及旧配置已完全删除，杀毒及防火墙关闭，加载后仍然闪退。
使用最新的70版chromium做测试，使用正常，没有出现闪退。

**Comment by Tiandians** [comment]
@free-vpn 我也是用新包。闪退时有两种情况：
1.打开页面较多时偶尔闪退
2.更新扩展程序时总是闪退
电脑没有杀毒软件，只有Windows Defender
系统版本：Skip预览通道 Windows10 1803 18219.1000
