### ISSUE TITLE
访问国内网址变慢？有这个问题么 ？ 

### ISSUE THREAD

**Issue by caofulin** [free-vpn/chrome#13]

**Comment by Tiandians** [comment]
当然会有，你的数据全部要到美国洛杉矶再回到国内。我浏览国内网站都会用另外的浏览器

**Comment by free-vpn** [comment]
是的 chromium加密所有流量 要兜一圈回来访问大陆网站

非常抱歉 因为也有一部分中国以外的用户会玩这个chromium 没有办法专门优化“国内”线路 最简单的解决方法就是专门为中国用户制作红芯版 不过我们没本事骗到2亿投资 又很懒 所以请大家用其他浏览器访问中国大陆网站 希望不会带来太大麻烦

**Comment by yumufeng** [comment]
> 是的 chromium加密所有流量 要兜一圈回来访问大陆网站
> 
> 非常抱歉 因为也有一部分中国以外的用户会玩这个chromium 没有办法专门优化“国内”线路 最简单的解决方法就是专门为中国用户制作红芯版 不过我们没本事骗到2亿投资 又很懒 所以请大家用其他浏览器访问中国大陆网站 希望不会带来太大麻烦

楼主有没有这样一种方法，弄一个访问网站集合列表？加入到这个集合里的用国外加速，没有加到的用国内的DNS？
