### ISSUE TITLE
已经挂了，求更新谢谢

### ISSUE THREAD

**Issue by he1226** [free-vpn/chrome#14]
谢谢谢谢，才用了几天

**Comment by Tiandians** [comment]
我这边网络状况正常，建议您重置浏览器

**Comment by free-vpn** [comment]
<img width="705" alt="screen shot 2018-09-12 at 9 39 35 pm" src="https://user-images.githubusercontent.com/41530829/45428715-647c7480-b6d4-11e8-8365-b2c4b3722913.png">

这周应该来得及

**Comment by free-vpn** [comment]
Hey pls try the latest build @he1226 

https://github.com/free-vpn/chrome/releases/tag/70.0.3538.9
