### ISSUE TITLE
新的经常崩溃

### ISSUE THREAD

**Issue by s0302102** [free-vpn/chrome#15]
隔一段时间整个浏览器自己关掉。请问是什么 问题

**Comment by s0302102** [comment]
69.0.3493.5
版本号

**Comment by younglifestyle** [comment]
我也有这个问题

**Comment by free-vpn** [comment]
马上就升到70，估计会好点

**Comment by free-vpn** [comment]
pls try the latest v70 stable build: https://github.com/free-vpn/chrome/releases/tag/70.0.3538.9

**Comment by s0302102** [comment]
v70的还是会呀，开两个网页放着，不知道什么时候就自己关掉了
