### ISSUE TITLE
Chrome扩展挂了吗？

### ISSUE THREAD

**Issue by Tiandians** [free-vpn/chrome#18]
Chromium版经常出问题，于是换了官方的Chrome并安装了Free-VPN，但是点Connect后就无法浏览任何网站，四个服务器都是这样。怎么回事？
![aaa](https://user-images.githubusercontent.com/35755846/45582333-4b481380-b8e0-11e8-825c-9d5e9127ff69.png)

**Comment by free-vpn** [comment]
@Tiandians 您好，chrome插件在中国大陆是无法正常工作的，因为DNS污染。Chromium主要就解决DNS污染问题。

**Comment by Tiandians** [comment]
@free-vpn 就是说不论使用Hosts还是Pure DNS都无法解决这个问题吗？

**Comment by free-vpn** [comment]
@Tiandians 我们自己试过https://dnscrypt.info/implementations，很有用。它先通过加密渠道拿上游正确的dns数据（8.8.8.8，1.1.1.1），对本机来说它又是dns服务器，也就是把本机的dns server设置成127.0.0.1。浏览器要访问twitter，先问127.0.0.1，twitter的ip是什么，如果有就直接返回结果，如果没有，dnscrypt会加密访问上游，拿到结果缓存在本机，并告诉浏览器正确结果，从而避免浏览器去查中国电信部门的dns服务。

DNS污染在windows上特别严重，就算把网卡设置里的dns server改成8.8.8.8也没用，不知道为什么windows进行域名解析时还是会得到脏数据。mac/linux好一点。

直接写/etc/hosts可以解决问题。但缺点很明显：1. 大型网站经常换ip或者有多个ip负载均衡，hosts文件无法及时更新，无法返回多个ip地址，默认只用第一个结果。2. 在没有其他人帮忙时，第一次正确的结果从哪里来？而且，其他人发布的hosts未必可信和及时。3. 不适合普通人

puredns不如dnscrypt，因为它是一个公共服务，本身就有被篡改和屏蔽的可能。为了验证puredns结果，还是需要dnscrypt这种本机运行的软件，或者ssh到一台国外服务器上验证。

相关资料：https://zh.wikipedia.org/zh-hans/域名服务器缓存污染

**Comment by Tiandians** [comment]
@free-vpn 了解了，非常感谢
