### ISSUE TITLE
两个BUG

### ISSUE THREAD

**Issue by itnewgay** [free-vpn/chrome#23]
希望能用chrome稳定版做.

**Comment by free-vpn** [comment]
@itnewgay 谢谢反馈，我们会评估dev稳定性，如果很糟糕，就用beta版，还是不行，就用stable版本。正常情况下stable比dev落后6周，换句话说，stable就是6周前通过google测试的dev版本。

**Comment by itnewgay** [comment]
> 请描述有关Bugs的信息。你不能不提供任何信息。
大佬， 没办法提供任何信息。  正常使用的情况下，打开任何一个新的网页都可能会闪退。  每天都是这样。 这几天已经先用SSR了。 重置浏览器都不行， 这个稳定性真的是太差了。 要是用chrome 稳定版估计会好很多。 这个dev真的是严重有问题 。    反映在我这里最常遇到的两个会闪退的问题是：
1。打开一个新标签，闪退。
2。 打开一个网页载入后闪退，或者没有载入完就闪退。  

非常的频繁。
