### ISSUE TITLE
安全问题

### ISSUE THREAD

**Issue by hezhizheng** [free-vpn/chrome#24]
是不是会劫持所有访问的流量

**Comment by itnewgay** [comment]
劫持你大爷

**Comment by hezhizheng** [comment]
> 劫持你大爷
你是作者吗？？？

**Comment by hezhizheng** [comment]
@itnewgay 你是作者吗？？？？

**Comment by yumufeng** [comment]
本地开了一个 127.0.0.1的服务器做DNS加密跳板，会统统去8.8.8.8拿到正确的服务器IP 所有都会去美国再回来，国内的建议不要用，国外的适合

**Comment by Tiandians** [comment]
@itnewgay 来到国外网站就别爆粗口了，况且这里是开发者社区，很丢人的


> 是的 chromium加密所有流量 要兜一圈回来访问大陆网站

@hezhizheng  我在Issues #13 中提到过这个问题
其实你使用任何VPN，你的数据都会通过VPN拥有者的服务器，但它们不会劫持你的流量

> 流量，就是网络上传输的数据量。正常上网时，数据会在网民的客户端与正确的网站服务器之间传输，我们才能浏览网页、下载歌曲、收看视频。如果你原本想访问A网站，但是有人偷偷做了手脚，让你实际上打开的是B网站，这就叫流量劫持。

根据百科对“流量劫持”的定位，VPN服务者不会劫持流量。因为你的流量不过是被加密，经过VPN服务器，再发送至正确的服务器而已。
即：客户端→SSL加密连接→VPN服务器→正确的网站
当然，VPN拥有者或许有权查看你和服务器之间的通讯，这些我就不大清楚了

**Comment by hezhizheng** [comment]
@yumufeng 国外的话貌似也不需要用这个吧  都可以直接访问

**Comment by hezhizheng** [comment]
@Tiandians 谢谢回答

**Comment by jake2003a** [comment]
@yumufeng 能说一下你开的本地127.0.0.1服务器的端口是多少吗？我加到下载软件里可以用来下载吗？

**Comment by jiari56** [comment]
@Tiandians 安全问题比较严重的，从服务提供商到服务器硬件商，都是安全隐患

**Comment by jiari56** [comment]
vpn的不安全应该是众所周知的吧

**Comment by free-vpn** [comment]
@hezhizheng http可以看到明文，https不可以，要做到劫持流量的同时不让用户发现，估计只有路由器和电信网络可以做到，浏览器里劫持流量会烧掉cpu。我们开放chrome私密功能给大家用是为了开心，劫持流量这种事搞得大家都不开心了

@Tiandians 谢谢回答

**Comment by hezhizheng** [comment]
@free-vpn 谢谢回复，其实在更新到71版本之后发现速度慢了很多，几乎打不开网站，一般的限速是多少？
