### ISSUE TITLE
能否改用CHROME稳定版本

### ISSUE THREAD

**Issue by itnewgay** [free-vpn/chrome#30]
如题。 现在的版本稳定性太差了

**Comment by free-vpn** [comment]
@itnewgay 您好，开发版确实容易崩溃。Google Chromium内部流程大致是这样的，稳定版69，beta版70，开发版71，在某个时间节点，测试团队会拿一份开发版去测试，没有大问题就进入beta版，继续测，都OK的话就变成稳定版，稳定版大约6周更新一次。也就是说，稳定版其实是6周之前通过测试的开发版。我们基本会跟着Google开发版走，所有的build都放在https://github.com/free-vpn/chrome/releases，您可以选择稍微旧一点的版本，稳定性可能会好点。

如果实在不能用，请具体告诉我们访问哪个页面浏览器会崩溃，谢谢！
