### ISSUE TITLE
已挂

### ISSUE THREAD

**Issue by MarcusPopilius** [free-vpn/chrome#5]
8月24日16时30分左右开始无法使用。

**Comment by Tiandians** [comment]
我也是这个问题。浏览器显示代理服务器出现问题，错误代码：ERR_PROXY_CONNECTION_FAILED，重置了也没办法

**Comment by free-vpn** [comment]
下周一或周二可以恢复

**Comment by taxiazhang** [comment]
我这也挂了，我看发布了mac的新版本，windows的也快了吧

**Comment by fdlzZ** [comment]
我还以为是我电脑出问题了，win7和win10都测试了，都挂了- -本来想看亚运会LOL转播的

**Comment by MarcusPopilius** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
今天不就是周二了吗？


    
        a#ntes-pcmail-signature-default:hover {
            text-decoration: underline;
            color: #199cff;
            cursor: pointer;
        }

        a#ntes-pcmail-signature-default:active {
            text-decoration: underline;
            color: #246fce;
            cursor: pointer;
        }
    




    在2018年8月25日 20:04，free-vpn<notifications@github.com> 写道： 


下周一或周二可以恢复

**Comment by free-vpn** [comment]
已经发布：https://free-vpn.github.io/chrome/

谢谢各位关心。
