### ISSUE TITLE
代理服务器出现问题

### ISSUE THREAD

**Issue by Tiandians** [free-vpn/chrome#6]
![default](https://user-images.githubusercontent.com/35755846/44580769-cd578780-a7cd-11e8-8990-9a6a179466dc.png)
从昨晚开始就这样，重置了好几遍也没办法上网

**Comment by liaaili** [comment]
我也是 下午开始不行的

**Comment by qiusister** [comment]
下午6点下班，开始不行了

**Comment by free-vpn** [comment]
下周一或周二可以恢复
