### ISSUE TITLE
不能登录了

### ISSUE THREAD

**Issue by Hanbird** [free-vpn/chrome#7]
已经无法正常使用了

**Comment by hfyqsy** [comment]
![image](https://user-images.githubusercontent.com/23046221/44614847-7b5f4200-a85f-11e8-9b6b-3b17636a82e3.png)

**Comment by Tiandians** [comment]
估计是FreeVPN的代理服务器出问题了，等官方回复吧。。。

**Comment by free-vpn** [comment]
mac: https://github.com/free-vpn/chrome/releases/tag/69.0.3493.5

windows: by next Tuesday (US Pacific Time, -16 hours on Beijing time)

thx

**Comment by KevinWorkSpace** [comment]
@free-vpn 
Thank you very much for your effort. Chromium really helps me a lot. Respect!!!

**Comment by Tiandians** [comment]
@free-vpn 
I support you. This is an excellent software.

**Comment by taxiazhang** [comment]
@free-vpn 
非常赞的fq应用，希望一直做下去

**Comment by wejust1027** [comment]
期待@free-vpn能继续这个项目，只想说，Chromium对我的帮助真的很——谢谢

**Comment by fdlzZ** [comment]
谢谢您的无私奉献！

**Comment by hubing130** [comment]
已经无法正常使用了

**Comment by Timo-China** [comment]
无法使用了

**Comment by free-vpn** [comment]
已经发布：https://free-vpn.github.io/chrome/

谢谢各位关心。
