### ISSUE TITLE
Chromium 无法打开任何页面了

### ISSUE THREAD

**Issue by syucom** [free-vpn/chrome#8]
另外，请问WINDOWS客户端还有修复计划吗？我在WIN、OSX、iOS、Android全部使用FREEVPN，目前只有WIN平台的都不能用了。。。。

**Comment by free-vpn** [comment]
已经发布：https://free-vpn.github.io/chrome/

windows vpn客户端可能会直接整合进chromium，目前还没有时间表，先用chromium应付一段时间。其他平台其实只有android没有任何阻碍，apple两个平台数字签名被苹果修改了，不能支持中国区apple ID，我们自行发布的DMG安装到中国用户机器上会自动崩溃。windows vpn数字签名也有问题，所以暂时先弄好浏览器。

**Comment by syucom** [comment]
非常感谢！

free-vpn <notifications@github.com> 于2018年8月28日周二 下午3:41写道：
